name: Post CHIMERA Tweet

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install tweepy
      - name: Run bot script
        env:
          TWITTER_USERNAME_A: ${{ secrets.TWITTER_USERNAME_A }}
          TWITTER_PASSWORD_A: ${{ secrets.TWITTER_PASSWORD_A }}
          TWITTER_USERNAME_B: ${{ secrets.TWITTER_USERNAME_B }}
          TWITTER_PASSWORD_B: ${{ secrets.TWITTER_PASSWORD_B }}
          TWITTER_USERNAME_C: ${{ secrets.TWITTER_USERNAME_C }}
          TWITTER_PASSWORD_C: ${{ secrets.TWITTER_PASSWORD_C }}
        run: python post_chimera_tweet.py
